config/routes.rb
Rails.application.routes.draw do
  devise_for :users , path:'/' #, path_name:{sign_in: 'login' , sign_out: 'logout' , sign_up: 'sign_up'}
  root to: 'recipes#index'

  get '/general_shopping_list' , to: 'general_shopping_list#index'
  get '/public_recipes' , to: 'public_recipes#index'

  resources :recipes, :foods do
    resources :recipe_foods
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :destroy, Recipe, user: user

    can :read, Recipe, &:public

    can :create, Recipe do |recipe|
      user == recipe.user
    end

    can :read, Recipe do |recipe|
      user == recipe.user
    end

    can :create, Food, user: user
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user, class_name: 'User'

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { only_integer: true }
  validates :quantity, numericality: { only_integer: true }
end

app/models/foods.rb
class Foods < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user, class_name: 'User'

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { only_integer: true }
  validates :quantity, numericality: { only_integer: true }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user, class_name: 'User'
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preperation_time, presence: true
  validates :cooking_time, presence: true
  validates :public, inclusion: [true, false]
  validates :public, exclusion: [nil]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe'
  belongs_to :food, class_name: 'Food'

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = current_user.foods.all
  end

  def new
    @foods = current_user.foods.all
  end

  def create
    para = params[:food]
    Food.create('name' => para['name'], 'measurement_unit' => para['measurement_unit'],
                'price' => para['price'], 'quantity' => para['quantity'], 'user' => current_user)
    redirect_to '/foods'
  end

  def destroy
    @food = Food.find_by(id: params[:id])
    @food.recipe_foods.destroy_all
    @food.destroy
    redirect_to '/foods'
  end

  def show; end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @amount = 0
    @recipe = Recipe.includes(:foods, :recipe_foods).find_by(id: params[:id])
    @recipe.recipe_foods.each do |food|
      @amount += food.food.price.to_i * food.food.quantity.to_i
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).order('created_at DESC').includes(:user, :recipe_foods)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def create
    recipe = Recipe.includes(:recipe_foods).find_by(id: params[:recipe_id])
    params.permit!
    para = params[:name]
    food = Food.find_by(id: para)
    quantity = params[:food]
    unless recipe.recipe_foods.exists?(food: food)
      RecipeFood.create('quantity' => quantity['quantity'], 'recipe' => recipe, 'food' => food)
    end
    redirect_to "/recipes/#{params[:recipe_id]}"
  end

  def new
    @food = Recipe.find_by(id: params[:recipe_id])
    authorize! :new, @food
    @recipe = Recipe.find_by(id: params[:recipe_id])
  rescue StandardError
    flash.now[:notice] = 'You do not have the necessary permissions to add new ingredients.'
    render('recipes/error')
  end

  def destroy
    recipe = Recipe.find_by(id: params[:recipe_id])
    food = recipe.recipe_foods.find_by(id: params[:id])
    food.destroy
    redirect_to "/recipes/#{params[:recipe_id]}"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes.all
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    authorize! :read, @recipe
  rescue StandardError
    flash.now[:notice] = 'You do not have the necessary permissions to view this page.'
    render('recipes/error')
  end

  def create
    recipe = params[:recipe]
    recipe['user'] = current_user
    params.permit!
    Recipe.create(recipe)
    redirect_to '/recipes'
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    authorize! :destroy, @recipe
    fdr = @recipe.recipe_foods.where(recipe_id: @recipe.id)
    fdr.destroy_all
    @recipe.destroy
    redirect_to '/index'
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.public = !@recipe.public
    @recipe.save
  end
end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= food.owner_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :owner_id, style: "display: block" %>
    <%= form.text_field :owner_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<%= render "forms/navbar"%>
<div class="list-food">
     <div class="buttons li-foo">
    <button><%= link_to "Add Food" , new_food_path %></button>
    </div>
    <table>
        <tr>
            <th>Foods</th>
            <th>Quantity</th>
            <th>Action</th>
        </tr>
            <%@foods.each do |food| %>
                    <tr>
                        <td><%= food.name %></td>
                        <td><%= food.quantity %> <%= food.measurement_unit %></td>
                        <td class="remove-modify">
                        <span class="remove"><%= link_to "Delete" , url_for(action: 'destroy' , id: food.id ) , data: {turbo_method: :delete}%></span>
                        </td>
                    </tr>
            <%end%>
    </table>
</div>

app/views/foods/new.html.erb
<%= render "forms/navbar"%>
<%= render "forms/forms" , locals:{recipe:@foods}%>

app/views/foods/update.html.erb
<h1>Foods#update</h1>
<p>Find me in app/views/foods/update.html.erb</p>

app/views/recipe_foods/new.html.erb
<%= render "forms/navbar"%>
<%= render "forms/form" , locals:{recipe:@recipe} , message:flash%>

app/views/recipes/edit.html.erb
<!-- app/views/recipes/edit.html.erb -->

<h1>Edit Recipe</h1>

<%= form_for(@recipe) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Recipe Name' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Recipe Description' %>
  </div>

  <div class="form-group">
    <%= f.label :preparation_time %>
    <%= f.number_field :preperation_time, class: 'form-control', placeholder: 'Preparation Time (minutes)' %>
  </div>

  <div class="form-group">
    <%= f.label :cooking_time %>
    <%= f.number_field :cooking_time, class: 'form-control', placeholder: 'Cooking Time (minutes)' %>
  </div>

  <div class="form-group">
    <%= f.label :public %>
    <%= f.check_box :public, class: 'form-check-input' %>
  </div>

  <!-- Add other form fields as needed -->

  <div class="form-group">
    <%= f.submit "Update Recipe", class: 'btn btn-primary' %>
  </div>

<!-- "Back to Home" button to redirect to the home page -->
  <div class="form-group"><%= link_to 'Back to Home', root_path, class: 'btn btn-secondary' %></div>
<% end %>

app/views/recipes/error.html.erb
<div class="row d-flex justify-content-center cust">
    <div class="alert alert-warning" role="alert">
        <%= flash[:notice] %>
    </div>
</div>

app/views/recipes/index.html.erb
<%= render "forms/navbar"%>
<div class="recipes-list">
    <ul class= "recipe-item-list">
        <% @recipes.each do |recipe| %>
            <li class="recipe-item">
                <div class="recipe-item-para">
                    <h3 class="recipe-h3-link"> <%= link_to recipe.name , "recipes/#{recipe.id}"%> </h3>
                    <%if can? :destroy , recipe%>
                        <button><%= link_to 'Remove' , url_for(action: 'destroy' , id: recipe.id ) , data: {turbo_method: :delete}%></button>
                    <%end%>
                </div>
                <div>
                    <p> <%= recipe.description%></p>
                </div>
            </li>
        <%end%>
    </ul>
</div>

app/views/recipes/new.html.erb
<%= render "forms/navbar"%>
<%= form_with(model: Recipe , url: "/recipes" ) do |f| %> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :preparation %><br />
    <%= f.text_field :preperation_time , autofocus: true%>
  </div>

  <div class="field">
    <%= f.label :cooking_time %><br />
    <%= f.number_field :cooking_time , autofocus: true%>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description , autofocus: true%>
  </div>

  <div class="custom-control custom-switch publi-switch">
            <%= f.check_box :public, class: "custom-control-input", id: "customSwitch1" , autofocus: true %>
            <label class="custom-control-label" for="customSwitch1">Public </label>
    </div>
  <div class="actions">
    <%= f.submit "Add Recipe" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<%= render "forms/navbar"%>
<div class="recipe-detail">
        <h2 class="recipe-title"><%= @recipe.name%></h2>
        <div class="detail">
            <div class="detail-item">
                <div>
                    <p>Preparation time : <%= @recipe.preperation_time%> hour</p>
                    <p>Cooking time : <%= @recipe.cooking_time%> hour</p>
                    <p class="rcp-step">Steps goes here. . .</p>
                </div>
                <%= form_with(model: @recipe, url: recipe_path(@recipe), method: :patch, id: 'recipe-form') do |form| %>
                <div class="custom-control custom-switch">
                        <%= form.check_box :public, class: "custom-control-input", id: "customSwitch1", data: { public: @recipe.public }  %>
                        <label class="custom-control-label" for="customSwitch1">Public </label>
                </div>
                <% end %>
            </div>
            <div class="buttons">
                    <button><%= link_to "Generate shopping list", url_for(general_shopping_list_path(id: @recipe.id)) %></button>
                    <button><%= link_to "Add ingredient" , "#{@recipe.id}/recipe_foods/new" %></button>
            </div>
        </div>
        <table>
            <tr>
                <th>Foods</th>
                <th>Quantity</th>
                <th>Value</th>
                <th>Action</th>
            </tr>
           <%@recipe.recipe_foods.includes(:food).each do |food| %>
                <tr>
                    <td><%= food.food.name %></td>
                    <td><%= food.food.quantity %> <%= food.food.measurement_unit %></td>
                    <td>$<%= food.food.price.to_i * food.food.quantity.to_i %></td>
                    <td class="remove-modify">
                        <%= link_to "Modify" %>
                        <span class="remove"><%= link_to "Remove" , "/recipes/#{@recipe.id}/recipe_foods/#{food.id}" , data: {turbo_method: :delete}  %></span>
                    </td>
                </tr>
           <%end%>
        </table>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= user.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this user', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<h1>Welcom</h1>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>