config/routes.rb
Rails.application.routes.draw do
  devise_for :users , path:'/' #, path_name:{sign_in: 'login' , sign_out: 'logout' , sign_up: 'sign_up'}
  root to: 'recipes#index'

  get '/general_shopping_list' , to: 'general_shopping_list#index'
  get '/public_recipes' , to: 'public_recipes#index'

  resources :recipes, :foods do
    resources :recipe_foods
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :destroy, Recipe, user: user

    can :read, Recipe, &:public

    can :create, Recipe do |recipe|
      user == recipe.user
    end

    can :read, Recipe do |recipe|
      user == recipe.user
    end

    can :create, Food, user: user
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user, class_name: 'User'

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { only_integer: true }
  validates :quantity, numericality: { only_integer: true }
end

app/models/foods.rb
class Foods < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user, class_name: 'User'

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { only_integer: true }
  validates :quantity, numericality: { only_integer: true }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user, class_name: 'User'
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preperation_time, presence: true
  validates :cooking_time, presence: true
  validates :public, inclusion: [true, false]
  validates :public, exclusion: [nil]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe'
  belongs_to :food, class_name: 'Food'

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = current_user.foods.all
  end

  def new
    @foods = current_user.foods.all
  end

  def create
    para = params[:food]
    Food.create('name' => para['name'], 'measurement_unit' => para['measurement_unit'],
                'price' => para['price'], 'quantity' => para['quantity'], 'user' => current_user)
    redirect_to '/foods'
  end

  def destroy
    @food = Food.find_by(id: params[:id])
    @food.recipe_foods.destroy_all
    @food.destroy
    redirect_to '/foods'
  end

  def show; end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def create
    recipe = Recipe.includes(:recipe_foods).find_by(id: params[:recipe_id])
    params.permit!
    para = params[:name]
    food = Food.find_by(id: para)
    quantity = params[:food]
    unless recipe.recipe_foods.exists?(food: food)
      RecipeFood.create('quantity' => quantity['quantity'], 'recipe' => recipe, 'food' => food)
    end
    redirect_to "/recipes/#{params[:recipe_id]}"
  end

  def new
    @food = Recipe.find_by(id: params[:recipe_id])
    authorize! :new, @food
    @recipe = Recipe.find_by(id: params[:recipe_id])
  rescue StandardError
    flash.now[:notice] = 'You do not have the necessary permissions to add new ingredients.'
    render('recipes/error')
  end

  def destroy
    recipe = Recipe.find_by(id: params[:recipe_id])
    food = recipe.recipe_foods.find_by(id: params[:id])
    food.destroy
    redirect_to "/recipes/#{params[:recipe_id]}"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes.all
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    authorize! :read, @recipe
  rescue StandardError
    flash.now[:notice] = 'You do not have the necessary permissions to view this page.'
    render('recipes/error')
  end

  def create
    recipe = params[:recipe]
    recipe['user'] = current_user
    params.permit!
    Recipe.create(recipe)
    redirect_to '/recipes'
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    authorize! :destroy, @recipe
    fdr = @recipe.recipe_foods.where(recipe_id: @recipe.id)
    fdr.destroy_all
    @recipe.destroy
    redirect_to '/index'
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.public = !@recipe.public
    @recipe.save
  end
end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/_form.html.erb
<%= form_with(model: @recipe.foods.includes(:user) , url: "/recipes/#{@recipe.id}/recipe_foods" ) do |f| %> 
  <%= select_tag(:name, options_for_select(current_user.foods.map { |food| [food.name, food.id] })) %>

  <div class="field">
    <%= f.label :Quantity %><br />
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit "Add Food" %>
  </div>
<% end %>

app/views/forms/_forms.html.erb
<%= form_with(model: @foods , url: "/foods" ) do |f| %> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :Unit %><br />
    <%= f.text_field :measurement_unit %>
  </div>

  <div class="field">
    <%= f.label :Price %><br />
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :Quantity %><br />
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit "Add Food" %>
  </div>
<% end %>

app/views/forms/_navbar.html.erb
<div class="pos-f-t">
      <nav class="navbar navbar-dark nava">
        <h1>Recipe App</h1>
        <div class="realroot">
           <%= link_to "New recipe" , new_recipe_path%>
           <%= link_to "Recipes" , recipes_path %>
           <%= link_to "Foods" , foods_path %>
           <%= link_to "Public recipes" , public_recipes_path %>
        </div>
        <%= button_to "Logout", destroy_user_session_path, :method => 'delete', data:{turbo: "false"} %>
      </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" , "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   
    <%= javascript_importmap_tags %>
    <script>
    window.onhashchange = function() {
      console.log("Load")
      location.reload();
    };
  </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>